@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOWVmMWQ2Mi05ZjYzLTRlOTQtODM5MC01YzdlNTVhNGVkNDMiLCJleHAiOjE3NzMxMzc4ODV9.sWoq5TPSukTpkZ4smNAtMJNYnBCoAXFWgOTSx4bHMQU
@api_url=http://localhost:5000
# @whatsapp_service=http://172.20.88.203:4000
@whatsapp_service=http://192.168.1.6:3000

###
POST {{api_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "preparation",
  "password": "password123",
  "source": "mobile"
}