@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhOWVmMWQ2Mi05ZjYzLTRlOTQtODM5MC01YzdlNTVhNGVkNDMiLCJleHAiOjE3NzMxMzc4ODV9.sWoq5TPSukTpkZ4smNAtMJNYnBCoAXFWgOTSx4bHMQU
@api_url=http://localhost:3000
# @whatsapp_service=http://172.20.88.203:4000
@whatsapp_service=http://192.168.1.6:3000
@basic_auth=YWRtaW46YWRtaW4=
@whatsapp_device_id=83e3110a-23d7-400a-932b-8bb25d32314c
# @api_url=https://pokayoke-api.hadirapp.com

###
GET {{api_url}}/setup HTTP/1.1

###
POST {{api_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "preparation",
  "password": "password123",
  "source": "mobile"
}

###
GET {{api_url}}/customers HTTP/1.1
Authorization: Bearer {{access_token}}

###
GET {{api_url}}/deliveries/hpm/lot?date=2026-01-28&scan_type=preparation&status=open
Authorization: Bearer {{access_token}}

###
GET {{api_url}}/deliveries/hpm/lot-all?scan_type=preparation&date=2026-02-11&page=1&limit=50
Authorization: Bearer {{access_token}}

###
GET {{api_url}}/deliveries?search=&page=1&perPage=10&sortCol=created_at&sortDir=DESC&dateFrom=2026-02-11&dateTo=2026-02-11&customerId=bbb0eaf7-c695-42ae-81ce-a4ee993d68e1 HTTP/1.1
Authorization: Bearer {{access_token}}

### 
GET {{api_url}}/parts/print-history/06a202ec-9a13-4f9a-955a-6c6d74058d0c?date=20260224&limit=1&sortBy=serialEnd&sortDir=DESC
Authorization: Bearer {{access_token}}

###
GET {{api_url}}/deliveries/export-raw?dateFrom=2026-02-09&dateTo=2026-03-08&sortCol=created_at&sortDir=DESC&customerId=bbb0eaf7-c695-42ae-81ce-a4ee993d68e1
Authorization: Bearer {{access_token}}

###
GET {{api_url}}/parts/label-colors HTTP/1.1
Authorization: Bearer {{access_token}}

###
POST {{api_url}}/deliveries/scan-barcode HTTP/1.1
Authorization: Bearer {{access_token}}

{
  "customerId": "bbb0eaf7-c695-42ae-81ce-a4ee993d68e1",
  "lot": "HPM 06202603000301",
  "deliveryYear": 2026,
  "userId": "f56c7eaf-b13c-48ea-a6f6-0b5791d4bf5f",
  "userName": "User preparation",
  "userRole": "preparation",
  "kasaiBarcode": "84211T86-K011M1202603040010",
  "customerBarcode": "26111001510300004000006V"
}

###
POST {{whatsapp_service}}/send/message HTTP/1.1
Content-Type: application/json

{"phone":"628996226977","message":"Hello world","is_forwarded":false,"duration":0}

### Whatsapp
GET {{whatsapp_service}}/app/status HTTP/1.1
Authorization: Basic {{basic_auth}}
X-Device-Id: 83e3110a-23d7-400a-932b-8bb25d32314c

### Whatsapp
GET {{whatsapp_service}}/devices/{{whatsapp_device_id}} HTTP/1.1
Authorization: Basic {{basic_auth}}
X-Device-Id: {{whatsapp_device_id}}

### Whatsapp
GET {{whatsapp_service}}/user/info?phone=6282267139345@s.whatsapp.net HTTP/1.1
Authorization: Basic {{basic_auth}}
X-Device-Id: {{whatsapp_device_id}}

### Whatsapp
GET {{whatsapp_service}}/user/my/groups HTTP/1.1
Authorization: Basic {{basic_auth}}
X-Device-Id: {{whatsapp_device_id}}

### Whatsapp
POST {{whatsapp_service}}/send/message HTTP/1.1
Content-Type: application/json

{"phone":"120363425711188214","message":"Hello world","is_forwarded":false,"duration":0}


