name = "pengamanan-api"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/index.js"

[env.production]
name = "pengamanan-api-prod"

[env.staging]
name = "pengamanan-api-staging"

[build]
command = "bun run build"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.ts", "**/*.js"]

[env.production.vars]
NODE_ENV = "production"
DATABASE_URL = ""
JWT_SECRET = ""
JWT_REFRESH_SECRET = ""

[env.staging.vars]
NODE_ENV = "staging"
DATABASE_URL = ""
JWT_SECRET = ""
JWT_REFRESH_SECRET = "" 