name: CI/CD Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  publish:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        working-directory: ./web
        run: pnpm install
      - name: Compile project
        working-directory: ./web
        run: pnpm build
        env:
          VITE_APP_ENVIRONMENT: ${{ vars.VITE_APP_ENVIRONMENT }}
          VITE_API_URL: ${{ vars.VITE_API_URL }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 05b0906ce2488aa5647a275a274c9436
          projectName: blokf
          directory: web/dist
          git: true
          branch: main
          wranglerVersion: "3.82.0"
